### ISSUE TITLE
Question about the Zenodo dataset.

### ISSUE THREAD

**Issue by WANG-Yuchen-Alice** [tduricic/homophily-lastfm#1]
Hi! 

The DOI of the db DOI: 10.5281/zenodo.5585638, that you mentioned in the pape cannot be found on Zenodo. May I seek your help to recheck and confirm the link? 

Thank you!

**Comment by WANG-Yuchen-Alice** [comment]
To add on, the db provided in this link seems to be deprecated.

https://developers.google.com/freebase

**Comment by tduricic** [comment]
> Hi!
> 
> The DOI of the db DOI: 10.5281/zenodo.5585638, that you mentioned in the pape cannot be found on Zenodo. May I seek your help to recheck and confirm the link?
> 
> Thank you!

It is available now, and notebooks in the repository are used to extend the datasets with additional information with the goal of studying homophily and link prediction, feel free to check them out.

**Comment by tduricic** [comment]
> To add on, the db provided in this link seems to be deprecated.
> 
> https://developers.google.com/freebase

Yes, it has been deprecated but the genre tags are still available in the LFM-1b_UGP dataset available here: http://www.cp.jku.at/datasets/LFM-1b/

**Comment by tduricic** [comment]
Hope this answers your questions :)
